name: hypotheek_dataobjects_berekeningen
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  freezed: ^2.4.1
  json_annotation: ^4.8.1
  # path: ^1.8.0
  fast_immutable_collections:
    path: ../fast_immutable_collections
  intl: ^0.18.1

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  lints: ^2.0.0
  test: ^1.21.0
